baseURL = 'https://blog.varigergo.hu'
languageCode = 'en-US'
title = "Gergő Vári's blog"

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"

[module]
	[[module.imports]]
		path = "github.com/vyberd/vyberpunk"
	[[module.imports]]
		path = "github.com/vyberd/blog"
	[[module.imports]]
		path = "github.com/vyberd/funnels"
	[[module.imports]]
		path = "github.com/vyberd/checkout"
	[[module.imports]]
		path = "github.com/vyberd/questionnaires"
	[[module.imports]]
		path = "github.com/vyberd/base"
	[[module.imports]]
		path = "github.com/vyberd/gallery"
	[[module.imports]]
		path = "github.com/vyberd/navbar"
	[[module.imports]]
		path = "github.com/vyberd/animation"
	[[module.imports]]
		path = "github.com/vyberd/input"

	[[module.imports]]
		path = "github.com/gergovari/varigergo-shared"

	[[module.imports]]
		path = "github.com/gergovari/blog-content"


[params.matomo]
url = "https://matomo.varigergo.hu"
id = 2

[security]
	[security.exec]
	osEnv = ".*"
