baseURL = 'https://blog.varigergo.hu'
languageCode = 'hu-HU'
title = 'Vári Gergő blogja'

[module]
[[module.imports]]
	path = "github.com/gergovari/vyberpunk"

theme = "vyberpunk"

[params.matomo]
url = "https://matomo.varigergo.hu"
id = 2
