baseURL = 'https://blog.varigergo.hu'
languageCode = 'en-US'
title = "Gergő Vári's blog"

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"

[module]
	[[module.imports]]
		path = "github.com/vyberd/vyberpunk"
	[[module.imports]]
		path = "github.com/vyberd/blog"
	[[module.imports]]
		path = "github.com/vyberd/input"

	[[module.imports]]
		path = "github.com/gergovari/varigergo-shared"
	[[module.imports]]
		path = "github.com/gergovari/blog-content"


[params.matomo]
url = "https://matomo.varigergo.hu"
id = 2

[params.mautic]
url = "https://mautic.varigergo.hu"

[security]
	[security.exec]
	osEnv = ".*"
