baseURL = 'https://blog.varigergo.hu'
languageCode = 'hu-HU'
title = 'Vári Gergő blogja'

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"

[module]
	[[module.imports]]
		path = "github.com/gergovari/vyberpunk"

	[[module.imports]]
		path = "github.com/gergovari/blog-content"
		[[module.imports.mounts]]
			source = "content/"
			target = "content/"

[params.matomo]
url = "https://matomo.varigergo.hu"
id = 2

[security]
	[security.exec]
	osEnv = ".*"
